### ISSUE TITLE
Geocode returns [0.0, 0.0]

### ISSUE THREAD

**Issue by danielbonnell** [alexreisner/geocoder#1298] opened 2018-06-07 18:06 UTC
Hi, I have the following setup for my `Prospect` model:

 ```
class Prospect < ApplicationRecord
   geocoded_by :ip_address do |obj, results|
        geo = results.first.try(:data)

        if obj.ip_address.present? && geo.present?
            obj.update_columns(latitude: geo['latitude'], longitude: geo['longitude'])
        end
    end
end
```
In `config/initializers/geocoder.rb` I have:

```
Geocoder.configure(
    language: :en,
    timeout: 3,
    use_https: true,
    lookup: :google,
    ip_lookup: :ipstack,
    ipstack: {
        use_https: false,
        api_key: ENV['IPSTACK_API_KEY']
    },
    google: {
        api_key: ENV['GOOGLE_API_KEY']
    }
)

```

If I try to geocode an instance of `Prospect` like so, I get invalid coordinates for a valid ip address.

```
prospect.ip_address
=> "10.189.169.232" # This is a Los Angeles IP address
prospect.geocode
=> [0.0, 0.0] # ???
```

I can't figure out why this is not working. It was working previously with `freegeoip` until recently. I've been over the documentation on using multiple providers several times and it's very confusing to say the least. For example, it's not at all clear how the gem determines which provider to use for `lookup` vs `ip_lookup` or if I need to specify which service to use for which function.

**Comment by alexreisner** [comment] 2018-06-07 18:53
The gem will [detect](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/query.rb#L65) whether you're trying to geocode an IP address or a physical address and use the appropriate lookup. Can you run `Geocoder.search("10.189.169.232")` to help determine whether the problem is in getting the data or in assigning it to the object?

**Comment by danielbonnell** [comment] 2018-06-07 19:06
Ok, thanks for that clarification on how it works.Here is the output of that command:

```
Geocoder.search("10.189.169.232")
=> [#<Geocoder::Result::Ipstack:0x000055bbc048d740 @data={"ip"=>"10.189.169.232", "type"=>"ipv4", "continent_code"=>nil, "continent_name"=>nil, "country_code"=>nil, "country_name"=>nil, "region_code"=>nil, "region_name"=>nil, "city"=>nil, "zip"=>nil, "latitude"=>nil, "longitude"=>nil, "location"=>{"geoname_id"=>nil, "capital"=>nil, "languages"=>nil, "country_flag"=>nil, "country_flag_emoji"=>nil, "country_flag_emoji_unicode"=>nil, "calling_code"=>nil, "is_eu"=>false}}, @cache_hit=nil>]
```

**Comment by alexreisner** [comment] 2018-06-07 19:11
I'm not getting results for that address from freegeoip or ipinfo.io either. Looks like a hole in the database.

Closing, because I think this is an API issue, not a gem issue.

**Closed by alexreisner** 2018-06-07 19:11 UTC

**Comment by danielbonnell** [comment] 2018-06-07 19:38
I have tons of others that fail too. I've also tried them with `ipinfo.io` and they still fail. Do you have any recommendations on better API providers or is there a way to configure the gem to try multiple providers until it either finds the address or fails?

**Comment by alexreisner** [comment] 2018-06-07 19:44
I'd recommend checking out any of the non-free solutions, but know that IP address is just not possible in 100% of cases, or even close to it. Eg: https://www.maxmind.com/en/geoip2-city-accuracy-comparison
