### ISSUE TITLE
Bing lookup doesn't raise an exception for some kinds of server errors

### ISSUE THREAD

**Issue by jamesgecko** [alexreisner/geocoder#841] opened 2015-04-16 22:53 UTC
If Bing's API fails to return something expected, the Bing lookup [just prints a warning](https://github.com/alexreisner/geocoder/blob/90e2ef1c82685c3a16bffb2c42e97bc210922f1b/lib/geocoder/lookups/bing.rb#L48). An exception would be more useful, especially if the server is complaining about a rate limit.

I glanced through the other lookup classes, and the [MapQuest](https://github.com/alexreisner/geocoder/blob/7143136f35bab70966abcb22c23933bce79c970b/lib/geocoder/lookups/mapquest.rb#L52) and [Google](https://github.com/alexreisner/geocoder/blob/90e2ef1c82685c3a16bffb2c42e97bc210922f1b/lib/geocoder/lookups/google.rb#L38) ones do raise exceptions.

**Comment by alexreisner** [comment] 2015-04-17 00:23
Sounds great. Would love a pull request for raising exceptions on various error conditions with Bing.

**Comment by peteb** [comment] 2015-04-21 11:42
Might this be related to #840? I'm using Bing and it seems to be caching nil.

**Comment by alexreisner** [comment] 2015-04-21 12:27
@peteb it looks related in that Bing doesn't use HTTP response codes well (which is part of the cause of  both issues), but a solution to this won't fix #840 (or vice versa).

**Comment by germsvel** [comment] 2018-01-10 20:09
@alexreisner how would you feel about raising a `Geocoder::Error` for a 403, 500, and 501? 

Bing seems to [support those](https://msdn.microsoft.com/en-us/library/ff701703.aspx), and at least it would notify the users of the gem that something is wrong. If you feel like that would be an improvement over just printing the warning, I'd be happy to take a stab at it and open a PR.

**Comment by alexreisner** [comment] 2018-01-10 21:00
I'm still open to a PR for this, but note that each of those response codes implies a different exception. Maybe something like this:

403: `Geocoder::RequestDenied`
500: `Geocoder::ServiceUnavailable`
503: `Geocoder::ServiceUnavailable`

but it really depends on the conditions under which Bing returns those codes (I'm going by generic HTTP definitions). Also, please be sure to use the `raise_error` method (see [the base lookup](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/base.rb) for an example).

**Comment by germsvel** [comment] 2018-01-16 16:54
Thanks for the response @alexreisner. And thanks for mentioning `raise_error`. I will certainly use that. 

Based on the bing documentation for [status codes](https://msdn.microsoft.com/en-us/library/ff701703.aspx) and for the [Locations api (by query)](https://msdn.microsoft.com/en-us/library/ff701711.aspx), it seems like a `Geocoder::RequestDenied` for a 403 and a `Geocoder::ServiceUnavailable` for 500, 503 would be a good fit for the errors. 

I've looked through bing's [common response descriptions](https://msdn.microsoft.com/en-us/library/ff701707.aspx), and I don't think there is any more information in the json response that we could use to determine which kind of error to raise (as is done for the [401 error](https://github.com/alexreisner/geocoder/blob/90e2ef1c82685c3a16bffb2c42e97bc210922f1b/lib/geocoder/lookups/bing.rb#L45)). I can, however, pass the `error_details` from bing to `raise_error` as the second argument to provide more context. I see that similar things are done in the [mapquest implementation](https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/lookups/mapquest.rb#L46)

**Closed** 2018-01-19 23:00 UTC
Labels: bug
