### ISSUE TITLE
.city does not return :sublocality with google as expected

### ISSUE THREAD

**Issue by benortiz** [alexreisner/geocoder#973] opened 2016-01-22 21:34 UTC
When querying Google with `.search` and coordinates `40.745338697450066, -73.9273452758789` (Queens, NY), `.city` returns `nil`. The expected result would be `Queens` as the [Google API returns](http://maps.googleapis.com/maps/api/geocode/json?address=40.745338697450066+-73.9273452758789&language=en&sensor=false) `Queens` as a `sublocality` and the [Google geocoder](https://github.com/alexreisner/geocoder/blob/7fd63edf2a27ec2bcc0d28ae2aa119d051623c1f/lib/geocoder/results/google.rb#L20-L30) seems configured to take from the `sublocality` field.

Let me know if you need further information.

## Reproduce

1. Get the query url:
  * `Geocoder::Lookup.get(:google).query_url(Geocoder::Query.new(40.745338697450066 -73.9273452758789"))`
1. Visit the URL
  * http://maps.googleapis.com/maps/api/geocode/json?address=40.745338697450066+-73.9273452758789&language=en&sensor=false
1. Check the results of the URL for `locality`, `sublocality`, `administrative_area_level_3`, or `administrative_area_level_2`.
  * `Queens` is a `sublocality`.
1. Compare to the results of the Geocoder.
  * `Geocoder.search("40.745338697450066 -73.9273452758789").try(:first).city`
  * returns `nil`

## Versions
Ruby: 2.2.4
Rails: 4.2.5
Geocoder: 1.2.14

**Comment by TrangPham** [comment] 2016-01-22 22:54
Hi @benortiz 

I could not reproduce your issue.
These are the steps I took:
```ruby
thu-mbp:geocoder thu$ irb
2.3.0 :001 > require 'geocoder'
 => true
2.3.0 :006 > Geocoder::Lookup.get(:google).query_url(Geocoder::Query.new("40.745338697450066, -73.9273452758789"))
 => "http://maps.googleapis.com/maps/api/geocode/json?language=en&latlng=40.745338697450066%2C-73.9273452758789&sensor=false"
2.3.0 :010 > Geocoder::Lookup.get(:google).search(Geocoder::Query.new("40.745338697450066, -73.9273452758789")).first.city
 => "Queens"
2.3.0 :011 > Geocoder.configure(lookup: :google)
 => {:timeout=>3, :lookup=>:google, :ip_lookup=>:freegeoip, :language=>:en, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :basic_auth=>{}, :logger=>:kernel, :kernel_logger_level=>2, :always_raise=>[], :units=>:mi, :distances=>:linear}
2.3.0 :013 > Geocoder.search("40.745338697450066, -73.9273452758789").first.city
 => "Queens"
```

Though when I tried using `.try` I did get an error.
```ruby
2.3.0 :014 > Geocoder.search("40.745338697450066, -73.9273452758789").try(:first).city
NoMethodError: undefined method `try' for #<Array:0x007f9c8402a8c8>
Did you mean?  trap
	from (irb):14
	from /Users/thu/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

Versions:
ruby 2.3.0
geocoder master branch (currently 1.2.14)

Would you mind trying without `.try`?

**Comment by benortiz** [comment] 2016-01-22 23:03
@TrangPham thanks for checking this out. The strangest thing just happened: it worked repeating the same steps that I outlined above with the `try`. It also worked without `try` for me. I don't understand what changed. Maybe it's a timeout error?

**Comment by TrangPham** [comment] 2016-01-22 23:05
No problem. Glad everything worked out. :) Closing this issue.

**Closed by TrangPham** 2016-01-22 23:05 UTC
