### ISSUE TITLE
Can't find near locations 

### ISSUE THREAD

**Issue by Igorpollo** [alexreisner/geocoder#1250] opened 2017-12-13 21:32 UTC
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
Are able to find near 

### Actual behavior

Getting the error `"exception": "#<ActiveRecord::RecordNotFound: Couldn't find Test with 'id'=near>",`

### Steps to reproduce

My model

```
class Test < ApplicationRecord

	reverse_geocoded_by :lat, :long
	after_validation :reverse_geocode  # auto-fetch address
end
```

My action

```
 def near
   @near = Test.near([22.844279, -43.306174], 20, :units => :km)
   render json: @near
  end
```

### Environment info

* Geocoder version: 1.4.5
* Rails version:  5.1.4
* Database (if applicable): sqlite

**Comment by alexreisner** [comment] 2017-12-13 22:08
This might be related to #1178. Could you try using `< ActiveRecord::Base` instead of `ApplicationRecord `?

**Comment by Igorpollo** [comment] 2017-12-13 22:27
@alexreisner I solved this...
It was a route problem. `/tests/near` trying to get tests by id beacause of ` resources :tests` in the routes.

So now, I'm facing another problem. A blank array

Got this in database: 

```
  "id": 2,
        "name": "sogra",
        "lat": "-22.833695",
        "long": "-43.313411",
```

This is my action using the same coordenates

```
 def near
   @near = Test.near([-22.844279, -43.306174], 100, :units => :km)
   render json: @near
  end
```
This is my model:

```
class Test < ApplicationRecord
	reverse_geocoded_by :lat, :long
end
```

It's returning blank array. Help pls

**Comment by alexreisner** [comment] 2018-01-11 17:35
I'm not sure exactly what's going on here but I suspect it's related to app code or what's in your database (the SQL query looks correct). Closing because not a bug or feature request.

**Closed by alexreisner** 2018-01-11 17:35 UTC
